### ISSUE TITLE
Debug intermedio della soluzione

### ISSUE THREAD

**Issue by danielegenta** [danielegenta/ProjectTPSI_Spider#1]
Direi che è ora di fare un debug completo del progetto prima di procedere all'implementazione di nuove funzioni.
Cosa: effettuare un controllo sulle funzionalità finora esistenti.
Come:effettuare varie partite.
Cosa cercare: bug, malfunzionamenti, stranezze e quant'altro.

**Comment by danielegenta** [comment]
Bug trovati: 
1)[RISOLTO]quando si "spostano" tutte le carte da una certa colonna, essa si rimpicciolisce e conseguentemente viene sfasata la width del progetto.
2)[RISOLTO]alcune volte (da verificare quando) alcune carte non risultano 'droppabili' anche se lo dovrebbero essere (anche senza effettuarare distribuzioni dal mazzo inferiore).
3)[RISOLTO]Ogni tanto dopo la distribuzione mazzi non riconosce le scale e perciò esse risultano NON spostabili, quando dovrebbero esserlo.
4)[RISOLTO]Se distribuendo un mazzo vengono impilate due carte dello stesso valore, risultano 'draggabili'.
5)[RISOLTO]Quando una colonna rimane vuota non si riesce e droppare carte sopra.
6)[RISOLTO]Quando l'ultima carta di una colonna viene droppata questa ha margin-top=0 ovvero non risulta incastrata alla carta precedente e viceversa quando una carta viene droppata su una colonna vuota questa risulta avere il margine negativo (cambiare dinamicamente classi).
7)[RISOLTO]Ogni tanto (evento non precisato) alcune carte risultano non draggabili/droppabili. (verificato dopo distribuzione carte), ad esempio se si sposta una carta, quella sotto risulta non draggabile.
8)[RISOLTO]Bug sulla distribuzione carte, una scala (54323) risulta draggabile.
9)[RISOLTO]Conseguentemente a vari spostamenti alcune scale risultano non draggabili.
10)[RISOLTO]Contamosse rimane fermo (es. a 15 mosse).

**Comment by danielegenta** [comment]
-Corretto il bug n.1 (definizione height e width in css).
-Corretto il bug n.2 (bastava aggiornare la proprietà draggable dell'ultima linea dopo lo spostamento di una carta).
-Corretto il bug n.3 (bastava aggiornare la proprietà draggable una volta trovata una scala).
-Corretto il bug n.5 (bastava ottimizzare le impostazioni di drop dei 'topdecks')
-Corretto il bug n.6 (bastava cambiare dinamicamente le classi negli eventi critici sopra citati).
-Corretto bug n.7, ora dopo la distribuzione carte non sono presenti errori di drag (bastava aggiornare l'abilitazione).
-Corretto il bug n.9 (occorreva misurare la lunghezza delle colonne in modo differente).
-Corretti i bug n. 4 e 8 (occorreva ottimizzare la distribuzione delle carte e creare una funzione di azzeramento).
-Corretto il bug n10 (occorreva ottimizzare la funzione di aumento mosse).

**Comment by Themite** [comment]
A me dopo aver distribuito le carte una volta sola le carte dai 10 in su non si muovono (Parte del bug n. 7)

**Comment by danielegenta** [comment]
## Ultimo 'bug' da segnalare, se si effettuano movimenti troppo rapidi con una carta questa risulta non droppabile...per ovviare al problema basta spostare un'altra carta ed il tutto viene riaggiornato.

## Aggiornamento: possibile che il bug sia stato risolto con un controllo sugli id.

Aggiornamento x2: risolto definitivamente.
