### ISSUE TITLE
Debug finale della soluzione

### ISSUE THREAD

**Issue by danielegenta** [danielegenta/ProjectTPSI_Spider#3]
In vista della consegna di domani sarebbe opportuna una verifica completa del funzionamento del progetto, come al solito se trovate bug scrivete un commento e come si è verificato.

**Comment by Themite** [comment]
So che è l'ultimo giorno Genta ma come avevo già detto prima secondo me lo sfondo del input del nome dovrebbe essere piu' scuro, e un altra cosa che avevo notato e quando inserisci il nome del giocatore se schiacci invio "come faccio sempre di solito" non entra nel gioco ma chiedi di nuovo l'insermento

**Comment by Themite** [comment]
Ah nella presentazione vi siete dimenticati di mettere anche levro,ma tanto missa che non se ne accorgerà perche non lo guardera :-1: .
E volevo chiedere se stavolta ci aggiungete un punto nella slide finale con "documentazione stili css"

**Comment by Themite** [comment]
Per il resto ottimo direi :+1: .
P.S. il movimento delle carte cosi fluido ci sta un casino :)

**Comment by danielegenta** [comment]
1) No, l'input fa continuità con il tab informazioni e poi fa troppo material design così.
2)L'invio è un problema, me ne ero già accorto...se riesco lo metto a posto.
3)Levrone aggiunto, me ne ero dimenticato.
4)Sarà fatto.

**Comment by Themite** [comment]
ah genta ho trovato un bug "se cosi si puo chiamare" in cui se tu andando avanti nel gioco fai un punteggio ex. 534 quando fai nuova partita cominci sempre con lo stesso punteggio. Peace

**Comment by Themite** [comment]
Comunque quelle 2 freccie di cui parla levro (NON SU GITHUB) anche a me compaiono

**Comment by Themite** [comment]
Ah genta ce ancora l'errore della cella vuota di cui abbiamo parlato

**Comment by danielegenta** [comment]
Allora:
1)il punteggio lo ho risolto
2)che browser usate?
3)puoi spiegare meglio? se è quello della distribuzione carte...è voluto

Ottimo lavoro Mite!

**Comment by Themite** [comment]
1)uso chrome
2) la distribuzione delle carte gente mi sembra di avertene già parlato prima comunque sarebbe quando una fila è vuota quando si vuole distribuire un altro mezzo dovrebbe dare errore
